### ISSUE TITLE
디자인 이슈

### ISSUE THREAD

**Issue by thechunsik** [open-transit/ourbus-web#34]
## 데스트탑
- [x] 사파리에서 본고딕 폰트가 명조로 보이는 현상 개선
- [x] 노선신청 페이지 상단에 기획한 현황판 추가 
- [x]  "눈뜨면광진 분당노선" 일 경우, 세부페이지 타이틀 영역에 “눈뜨면광진”만 있음 (카드 제목과 동일한 형식으로)
- [x] 트위터 컬러: #35caff 
- [x] 지도: 눈뜨면도착모양 마커로 교체
- [x] 자주 묻는 질문: 디자인 스타일 반영
- [ ] 상단 메뉴바 선택된 메뉴 텍스트 폰트: heavy, #00bbb3
- [x] 캠퍼스 세부페이지 우측 스티키영역: 수요조사링크 카드&이미지 넣기 (demand_link_image.jpg)
- [x] 메인 헤더 검색창 검은글씨로 "원하는 지역의 동을 입력하세요(승차 혹은 하차를 원하는 곳)" 있는데 이거 그냥 삭제하고 노선찾아보기처럼 검색창 안에 텍스트로 해결하는것이 더 예쁠듯!!

- [x] 월요일에 전달한 jpg 디자인 가이드 > 픽셀, 폰트 디자인 및 세부 요소 반영
  - [x] [메인페이지]
    - [x] 타이머 글줄 간격 조정, 
    - [x] "X월 탑승 신청 종료 까지" 텍스트사이즈 1.44em으로, 폰트 Extra light(가장 얇은)으로 
    - [x] 추가: 사용후기 배경영역 컬러 #F4F4F4 로 변경
    - [x] 제목 스타일 추가 (핫이슈노선, 사용후기) : Font-Size: 1.56 em / Color: #565656 / Letter-Spacing: 0.08 em (글자 사이 멀어지게!!)
    - [x] 헤더 "눈뜨면도착은어떤서비스인가요?" : 폰트 Extra light(가장 얇은) / #979797
    - [x] 사용후기 "눈뜨면" font: light "도착": bold / 주소현 등 사용자 이름
    - [x] 사용후기 본문 텍스트 왼쪽 여백과 오른쪽 여백이 동일하게 (현재 오른쪽 영역이 더 큼)
    - [x] '핫이슈노선' 제목 스타일 처럼 '사용후기' 제목 스타일 옆에 디바이더 선 길이 줄이기
    - [x] 상단 "아직도 아침에 서서가니" 이미지 소스의 중앙 정렬이 안맞는 것 같은데, 소스 확인해보기 @예연
  - [x] [푸터]
  - [x] [노선찾아보기]
  - [x] [노선 상세 페이지] 
    - [x] 제목 영역, 현황판 생기면서 " | 8월 탑승 신청" 부분 삭제. 타이틀 콘텐츠 구성 가이드 이미지 확인
    - [x] 제목 여역과 현황판 사이에 디바이더 (화면 양 끝까지)
    - [x] 제목영역 배경 컬러 지정 : #f7f7f7 (슬랙 참고)
    - [x] 현황판
    - [x] 댓글, 뉴스피드 더보기 기능
    - [x] 댓글, 뉴스피드 부분 배경 컬러&스타일 적용
    - [x] 노선도 이미지 영역: 사진 비율이 변형 안되고 비율 유지되며 축소되게
  - [x] [노선 결제] : 전체적인 디자인 반영 (슬랙 참고)
  - [x] [계정]
  - [x] [회원가입, 로그인] 카드 여백 간격 조정

- [x] 프로필 이미지 용량이 큰 경우 로딩이 너무 김 (400x400정도로 크롭한 사진을 서버에 저장하고 불러오는 방식으로..?)
- [x] 프로필 사진은 원형 모양으로 크롭
- [x] '계정-결제 정보 설정' 메뉴 페이지 추가
- [ ] 프로필 조회 페이지 띄우기
- [x] 메인페이지 상단 "눈뜨면도착은어떤서비스인가요?"클릭 후 내려오면 민트색 영역이 상단 메뉴바 덮는 현상 개선
- [ ] 내계정 왼쪽 제목 설명 아이콘 "탑승신청현황"은 Sign in icon "프로필수정"은 User icon, "탈퇴하기"는 Minus Circle icon
- [x] 내계정-결제정보 제목 타이틀도 나머지 메뉴 제목 크기와 동일하게 사이즈 키우기
- [ ] 노선 상세 현황판, 지도 사이에 회색 0.5px line 다시 보이게
- [ ] 프로필 이미지 마우스 호버하면 사용자명 보이게
- [ ] 출발지 모아보기 텍스트 폰트 400으로 줄이기
- [ ] 카드UI 운행달성까지 정렬
- [ ] 캠퍼스>찾는노선이 없나요? 카드  hover하면 마우스 포인트 변경
- [ ] 푸터 opentransit 흰색글씨로
- [ ] 메인 찾아보기 기능이 안됨?
- [ ] 소개영상 보도자료 (보도자료는 뉴스 제목, 날짜만 추려서 목록 faq텍스트 스타일로. 뉴스 본문 링크로 가기)
- [ ] 메인 카드 "탑승하기 버튼" "자세히보기"로
- [ ] 댓글 10개, 뉴스피드 8개로 제한
- [ ] 메인 "핫이슈노선" > "인기노선"으로
- [ ] 푸터 라인하이트 조금 더 주기
- [ ] 대학인증 팝업&메세지
- [ ] 프로필이미지 수정 기능이 안됨!
- [ ] 총학제휴리본컬러 파란색으로 #1082ff
- [ ] 수요조사 title 텍스트컬러 white
- [ ] 노선밀어주기 버튼 아래 설명 텍스트: 참여자 모집은 20일까지이며 모집 성공시 결제됩니다. 운행 달성시 전액 환불됩니다."
- [ ] 결제완료 > "마이페이지" 텍스트 "내정보 > 탑승신청현황"

## 모바일
- [x] 캠퍼스 대학 세부 페이지 디자인 정리 (카드 UI 메인페이지처럼)
- [x] 캠퍼스 대학 세부 헤더
- [x] 모바일 뷰 기능 완성: 왼쪽의 메뉴 슬라이드 선택 후 자동 화면 전환이 안되는 현상
- [x] 메인 헤더 "원하는 지역의 동을입력하세요(승하차를 원하는 - 곳"으로 줄바꿈되며 떨어지는 현상 개선. 폰트 사이즈 줄이기)
- [x] 캠퍼스 링크 카드 "눈뜨면도착on캠-퍼스" 끊김현상 개선
- [x] 노선카드 "운행달성까지" 줄 정렬이 "%"와 같게 (슬랙참고 p1)
- [x] 왼쪽 메뉴 슬라이드 영역 "내계정" 추가
- [x] 캠퍼스 대학 리스트 카드 양쪽으로 길이 늘이기  (슬랙참고 p2)
- [x] 대학 세부 페이지 상단 텍스트 디자인 정리 (슬랙참고 p3)
- [x] 푸터 디자인 정리 (슬랙참고 p4)
- [x] 노선상세 "노선 밀어주기" 버튼 오른쪽으로 길이 늘이기 (좌우 여백이 다름)
- [x] 페이스북공유, 트위터공유 버튼 길이도 좌우 여백이 다름
- [x] 모바일 사파리에서 노선 결제 부분 탑승하기 버튼 텍스트가 왼쪽으로 치우치는 현상 (슬랙참고 p5) 
- [x] 노선선 결제 부분 전체적인 디자인 정리 (슬랙참고 p6)
- [x] 노선신청 모바일일때 노선도, 모바일용 노선도로 교체 (apply>line_example_mobile.jpg)

- [ ] 푸터 텍스트 잘림 현상
- [ ] 오른쪽 네비바 폰트컬러 555555
- [ ] 아이폰에서 카드UI깨지는 현상 개선
